@host = http://localhost:3000

Get {{host}}/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoic2hlZGluaG9zaGVkcmFjaEBnZG1haWwuY29tIiwiZmlyc3RuYW1lIjpudWxsLCJsYXN0bmFtZSI6bnVsbCwiaWF0IjoxNjg5NDc0NTI0LCJleHAiOjE2ODk0NzgxMjQsImF1ZCI6IkJvb2ttYXJrLWZyb250ZW5kIiwiaXNzIjoiQm9va21hcmstYmFja2VuZCJ9.8EMYtDYZU8eMjrkjZuIZ3vhSBH9GxRtNqBqo27b_Yfg
